### ISSUE TITLE
link to oneagent-sdk in README is a 404

### ISSUE THREAD

**Issue by warn4n** [Dynatrace/OneAgent-SDK-for-Java#1]
link to oneagent-sdk in README is a 404

**Comment by ghost** [comment]
thanks warn4n. we know and aware about it. linked repo is currently private, but will be published in next weeks. will close issue then ...

greetings alram

**Comment by christian-schwarzbauer** [comment]
https://github.com/Dynatrace/OneAgent-SDK repository is now public
