### ISSUE TITLE
Not able to run oneagentsdk.rb

### ISSUE THREAD

**Issue by aditi1103** [Dynatrace/OneAgent-SDK-for-Java#12]
unable to run oneagentsdk.rb using truffleruby
error "undefine method callback ,typedef and others"

**Comment by SonjaChevre** [comment]
Hi, this seems to have been posted in the wrong GitHub project (OneAgent SDK for Java). 

Closing since duplicate from: https://answers.dynatrace.com/spaces/482/dynatrace-open-qa/questions/217837/on-running-oneagentsdkrb-using-trufflruby-there-is.html - will add a comment there.
