### ISSUE TITLE
Question: Dynatrace tracers with Vertx

### ISSUE THREAD

**Issue by hegderaj** [Dynatrace/OneAgent-SDK-for-Java#16]
Hi,
 
We are using Dynatrace OneSDK Java agent for pushing tracing data to Dynatrace with reactive framework Vertx (https://vertx.io/). We are capturing the incoming request data with OneAgent tracer incoming web request. We are creating tracer in one thread and we are ending the tracer in a different thread (can be picked by any thread in vertx event-loop).
We are able to see the incoming request on Dynatrace dashboard, however we see below errors in Dynatrace dashboard

`Some data could not be collected or transmitted. This is most likely due to a resource congestion on network, host or process level in your monitored environment (Error codes: C1, A5)`

Also we see below warning in our application logs,
 
 ```
[d93ae85e] warning [native] methodExit: PATH  EXEC  tagId(12) sensorId(13) HPurePath(0x0000000d00000002), was called with SerialNo(2032) which should be SerialNo(2036), Current NODE: SDK Method depth(1) serialNo(2036) unused(FALSE) aggr[excl(TRUE) info(FALSE) root(FALSE) fin(FALSE)] method[0x48ad19521e8c01af,OneAgent SDK.Incoming web request, cat=None, art(TRUE)] contentChged(TRUE) Attachments(WebRequestAttachment ) 
[d93ae85e] warning [native] PATH  EXEC  tagId(12) sensorId(13) HPurePath(0x0000000d00000002) inconsistency (MethodExitMissing): Path ended, but current method node misses exit call NODE: SDK Method depth(1) serialNo(2036) unused(FALSE) aggr[excl(TRUE) info(FALSE) root(FALSE) fin(FALSE)] method[0x48ad19521e8c01af,OneAgent SDK.Incoming web request, cat=None, art(TRUE)] contentChged(TRUE) Attachments(WebRequestAttachment )
```

When we change our code as below to end the tracer in the same thread as we created (tracer end after a synchronous processing), we are not getting errors in dashboard and application logs.

```
try {
 // create tracer
} catch {
// tracer error
} finally {
// end tracer
}

```
Does Dynatrace tracers should be ended in the same thread as created or can we end them with object reference in some other thread?
 
Thanks,
Rajesh

**Comment by Oberon00** [comment]
Yes, all Dynatrace tracers must be used from the thread they were created on only. This includes starting, ending, and retrieval of tags.

**Comment by hegderaj** [comment]
Thank you for quick response.

**Comment by hegderaj** [comment]
Is there a plan to support in future for reactive applications where tracers can span over multiple threads?

**Comment by Oberon00** [comment]
Sorry, at the moment this is not on our road map. See also https://answers.dynatrace.com/idea/198106/planned-features-for-oneagent-sdk.html
