### ISSUE TITLE
Why are CustomServiceTracers not implemented?

### ISSUE THREAD

**Issue by AdrianSchneble** [Dynatrace/OneAgent-SDK-for-Java#22]
The [generic Dynatrace OneAgent SDK API ](https://github.com/Dynatrace/OneAgent-SDK) has so-called ["Custom Service Tracers"](https://github.com/Dynatrace/OneAgent-SDK/#trace-custom-services):

> ### Trace Custom Services
> You can use the SDK to trace custom service methods. A custom service method is a meaningful part of your code that you want to trace but that does not fit any other tracer. An example could be the callback of a periodic timer.

This seems to only be implemented by the [C/C++](https://github.com/Dynatrace/OneAgent-SDK-for-C#trace-custom-service-methods) and [Python](https://github.com/Dynatrace/OneAgent-SDK-for-Python#custom-services) language specific SDKs, but not by this project, the Java SDK (nor by the .NET or the Node.js implementation, but those are not relevant for me).

However, the [generic API documentation](https://github.com/Dynatrace/OneAgent-SDK/blob/master/README.md) states that "the API is available in Java language for reference purposes", and the linked API folder contains the [CustomServiceTracer.java](https://github.com/Dynatrace/OneAgent-SDK/blob/master/api/com/dynatrace/oneagent/sdk/api/CustomServiceTracer.java) interface.

Is there any specific reason why this custom tracer is not implemented by the Java SDK, contrary to what the generic SDK documentation suggests? I'll be contacting the Dynatrace contact partner assigned to the company I work for about this as well, but I figured I might as well open an issue here, since this is where it should be implemented as far as I can tell.

**Comment by z1c0** [comment]
Hi Adrian,

the linked API interface [(CustomServiceTracer.java)](https://github.com/Dynatrace/OneAgent-SDK/blob/master/api/com/dynatrace/oneagent/sdk/api/CustomServiceTracer.java) that you found, serves primarily a specification purpose and the fact that it's specified in Java does not necessarily mean that the respective feature is actually available in the [OneAgent SDK for Java](https://github.com/Dynatrace/OneAgent-SDK-for-java). Sorry, I know that this is not ideal.

A better overview of the feature implementation status across languages can be found here:

https://answers.dynatrace.com/spaces/483/dynatrace-product-ideas/idea/198106/planned-features-for-oneagent-sdk.html

Tracing of custom services is currently not available for Java and also not on the immediate roadmap.
@SonjaChevre can probably shed more light on this.

Best
Wolfgang

**Comment by SonjaChevre** [comment]
Hi Adrian,

in addition to what Wolfgang commented, you can configure custom service for Java & .NET directly in Dynatrace - without using the SDK. Have a look at the documentation: https://www.dynatrace.com/support/help/how-to-use-dynatrace/transactions-and-services/configuration/define-custom-services/

This is why implementing custom services in Java in the OneAgent SDK has been a lower priority for us at the moment. 

Sonja
