### ISSUE TITLE
Metrics API access

### ISSUE THREAD

**Issue by orneryd** [Dynatrace/OneAgent-SDK-for-Java#23]
The documentation states that the metrics API is available in preview. However, when I asked to get on that preview version, I was informed by support that it hasn't even been started yet. 

Is there a reason the documentation states it's available in preview when it hasn't been started yet?

![image](https://user-images.githubusercontent.com/1736223/78585339-89709500-77ee-11ea-81bd-bd5e5c7157f9.png)
![image](https://user-images.githubusercontent.com/1736223/78585347-8bd2ef00-77ee-11ea-80aa-2e74c346cbcc.png)
![image](https://user-images.githubusercontent.com/1736223/78585353-8d9cb280-77ee-11ea-9c39-b583c3164769.png)

**Comment by arminru** [comment]
Hi Tim!

This repository, OneAgent-SDK-**for-Java**, does not state anything about the Metrics feature available in other versions of the OneAgent SDK. The page you are referring to is indeed the cross-language specification as stated in the first paragraph there: https://github.com/Dynatrace/OneAgent-SDK#how-to-use-this-repository
It further says that not all features are available in all of the language implementions here: https://github.com/Dynatrace/OneAgent-SDK#features
> The feature sets differ slightly with each language implementation - see the respective language-specific documentation for feature availability. More functionality will be added over time, see Planned features for OneAgent SDK for details on upcoming features.

The Metrics API is currently not available in the OneAgent SDK for Java as correctly stated by my colleague. Unfortunately I cannot give you any ETA or roadmap insights on that. Please consult your Dynatrace representative for further information. Thanks!
