### ISSUE TITLE
invalid state: START_SUBPATH_FAILED

### ISSUE THREAD

**Issue by ShivaKumarPeddi** [Dynatrace/OneAgent-SDK-for-Java#27]
We are seeing this exception in our logs. 

[4cd16d98] end failed, invalid state: START_SUBPATH_FAILED

One Agent SDK Version: 1.8.0
Dynatrace Agent version : 1.219.134

Can someone help on this pls

**Comment by z1c0** [comment]
Hi,
for us to analyze this problem, more information is required.
Please contact your Dynatrace support person for that.
