### ISSUE TITLE
Support for Java 11 or later LTS versions

### ISSUE THREAD

**Issue by rajivbandi** [Dynatrace/OneAgent-SDK-for-Java#29]
**Is your feature request related to a problem? Please describe.**
The documentation says Java 1.6 or higher is supported. There have been multiple changes in Java from Java 9 onwards.
Hence, is OneAgent-SDK-for-Java supported with current Java LTS versions like Java 11, 17, etc supported ?
If yes, could you please specify which versions are supported ?
If no, please specify by when are you planning to support these versions ?

Currently we are looking for Java 11 support at the earliest.

**Comment by Oberon00** [comment]
Did you run into any problems with Java 11?
We actually test the SDK with different JVMs and Java 11 should work. And "Java 1.6 or higher" does include Java 11.

**Comment by Oberon00** [comment]
Closing, as there was no further feedback. Java 11 is supported & expected to work just fine.
